/// Flutter icons EgCons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EgCons
///      fonts:
///       - asset: fonts/EgCons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EgCons {
  EgCons._();

  static const _kFontFam = 'EgCons';
  static const _kFontPkg = null;

  static const IconData achievement = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData currency = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData template1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData template2 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trading = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData champion_cup = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
